#**Laboratorio: Valores y Vectores Propios**


In [1]:
#Importar librerías necesarias para la práctica

import numpy as np


##**1. Valores y vectores propios**

La función de Numpy *linalg.eig(a)* recibe como parámetro una matriz cuadrada **A** y devuelve dos arreglos uno con los valores propios y el otro con los vectores propios. También se puede utilizar esta función de manera que solo devuelva sólo uno de los dos arreglos:

* Para los vectores propios: *np.linalg.eig(a).eigenvectors*
* Para los valores propios:  *np.linalg.eig(a).eigenvalues*

**1.1 Ejemplo:** El siguiente ejemplo muestra cómo se puede utilizar esta función.  Considere la siguiente matriz:
\begin{align}
 M=\begin{pmatrix}
 7 & 9 & -4 \\
 8 & 2 & 6 \\
 18 & 7 & 3 \\
\end{pmatrix}
\end{align}

Esta matriz en particular no es simétrica y es cuadrada. También, vamos a imprimir su contenido. Note que, para esta matriz, los valores propios son números complejos. El código fuente se presenta a continuación:


In [2]:
#Definir la matriz M
M = np.array([[7,9,-4],[8,2,6],[18,7,3]])

#Calcular  los valore sy vectores prooios
result = np.linalg.eig(M)

#Imprimir en pantalla el resultado de la función linalg.eig(M)
print(result)

EigResult(eigenvalues=array([14.17939731+0.j        , -1.08969865+5.35864695j,
       -1.08969865-5.35864695j]), eigenvectors=array([[-0.26782667+0.j        , -0.26296572+0.39356216j,
        -0.26296572-0.39356216j],
       [-0.56159037+0.j        ,  0.29330944-0.51032663j,
         0.29330944+0.51032663j],
       [-0.78286981+0.j        ,  0.65535804+0.j        ,
         0.65535804-0.j        ]]))


In [3]:
# Ahora calcular los valores y vectores propios de forma separada
val , vec = np.linalg.eig(M)
#Imprime los resultados para cada función por aparte de una manera más organizada
for i in range(len(val)):
    print("Valor Propio",i+1,":", val[i])
    print("Vector Propio",i+1,":", vec[:,i])

Valor Propio 1 : (14.179397308970753+0j)
Vector Propio 1 : [-0.26782667+0.j -0.56159037+0.j -0.78286981+0.j]
Valor Propio 2 : (-1.0896986544853844+5.35864695426102j)
Vector Propio 2 : [-0.26296572+0.39356216j  0.29330944-0.51032663j  0.65535804+0.j        ]
Valor Propio 3 : (-1.0896986544853844-5.35864695426102j)
Vector Propio 3 : [-0.26296572-0.39356216j  0.29330944+0.51032663j  0.65535804-0.j        ]


**1.2 Ejemplo:** Ahora considere una matriz $B$:
\begin{align}
 B=\begin{pmatrix}
 1 & 2 & 3 \\
 2 & 5 & 0 \\
 3 & 0 & 1 \\
\end{pmatrix}
 \end{align}

Esta matriz es simétrica y cuadrada. Calculemos los valores y vectores propios. Note que los valores propios de esta matriz son reales. Recuerde que los valores propios de una matriz simétrica SIEMPRE son números reales.

In [4]:
B= np.array([[1,2,3],[2,5,0],[3,0,1]])

#Calcular los valores y vectores propios de forma simultanea
result= np.linalg.eig(B)

#Imprime en pantalla el resultado de la función linalg.eig(B)
print(result)


EigResult(eigenvalues=array([-2.28699044,  3.11942518,  6.16756526]), eigenvectors=array([[ 0.72389106, -0.49179281, -0.4838611 ],
       [-0.19868039,  0.52302393, -0.82883779],
       [-0.6606874 , -0.69612197, -0.28090275]]))


In [5]:
#Calcular los valores y vectores propios de forma separada
val,vec=np.linalg.eig(B)


#Imprime los resultados para cada función por aparte de una manera más organizada
for i in range(len(val)):
    print("Valor Propio",i+1,":", val[i])
    print("Vector Propio",i+1,":", vec[:,i])

Valor Propio 1 : -2.286990441636361
Vector Propio 1 : [ 0.72389106 -0.19868039 -0.6606874 ]
Valor Propio 2 : 3.119425178408482
Vector Propio 2 : [-0.49179281  0.52302393 -0.69612197]
Valor Propio 3 : 6.167565263227874
Vector Propio 3 : [-0.4838611  -0.82883779 -0.28090275]


**Ejercicios de práctica**
Para la siguientes matrices hallar e imprimir en pantalla los valores y vectores propios.

Matriz 1

\begin{align}
 \begin{pmatrix}
 8 & 0 & 0 \\
 0 & 2 & 0 \\
 0 & 0 & 3 \\
\end{pmatrix}
 \end{align}


Matriz 2

\begin{align}
 \begin{pmatrix}
 4 & 7 & 6 \\
 0 & 5 & 8 \\
 5 & 1 & 3 \\
\end{pmatrix}
 \end{align}


In [7]:
# Definición de matrices
M1 = np.array([[8,0,0],[0,2,0],[0,0,3]])
M2 = np.array([[4,7,6],[0,5,8],[5,1,3]])

# Vectores y valores propios
eival1, eivec1 = np.linalg.eig(M1)
eival2, eivec2 = np.linalg.eig(M2)

# Imprimimos los hallazgos
print('*'*20)
print('M1')
print('*'*20)
for i in range(len(eival1)):
  print(f'Autovalor {i+1} = {eival1[i]}')
  print(f'Autovector {i+1} = {eivec1[:,i]}')

print('*'*20)
print('M2')
print('*'*20)
for i in range(len(eival2)):
  print(f'Autovalor {i+1} = {eival2[i]}')
  print(f'Autovector {i+1} = {eivec2[i]}')

********************
M1
********************
Autovalor 1 = 8.0
Autovector 1 = [1. 0. 0.]
Autovalor 2 = 2.0
Autovector 2 = [0. 1. 0.]
Autovalor 3 = 3.0
Autovector 3 = [0. 0. 1.]
********************
M2
********************
Autovalor 1 = (-0.15569502048608974+3.5790226752395164j)
Autovector 1 = [-0.07684054-0.50351302j -0.07684054+0.50351302j -0.74257236+0.j        ]
Autovalor 2 = (-0.15569502048608974-3.5790226752395164j)
Autovector 2 = [ 0.67706845+0.j  0.67706845-0.j -0.4943956 +0.j]
Autovalor 3 = (12.31139004097218+0j)
Autovector 3 = [-0.43634481+0.30290542j -0.43634481-0.30290542j -0.45183988+0.j        ]


**Nota:** En el caso de la matriz 1, que es una matriz diagonal, es importante mencionar que al hallar sus valores y vectores propios estos deben ser los mismos elementos de la diagonal y los vectores canónicos para $R_3$ respectivamente.

##**2. Reconstrucción de matrices a partir de sus valores y vectores propios**

Una matriz simétrica $Q$ se puede representar como  $Q=VAV ^{-1}$, en donde:

* V es la matriz cuyas columnas son los vectores propios de Q.
* A es una matriz diagonal cuyos elementos son los valores propios de Q.




**2.1 Ejemplo:** Consideremos la siguiente matriz:
\begin{align}
 \begin{pmatrix}
 3 & 0 \\
 0 & -5 \\
\end{pmatrix}
 \end{align}

Verifiquemos cómo podemos obtener la reconstrucción de una matriz simétrica a partir de sus valores y vectores propios.

In [ ]:
#Se declara la matriz
C=np.array([[3,0],[0,-5]])

#Se halla los valores y vectores propios
a, V = np.linalg.eig(C)

#Se agregan los valores propios en la diagonal de una matriz diagonal
A=np.diag(a)

#Se halla la inversa de V
Vinv=np.linalg.inv(V)

#Solamente con V, A y Vinv reconstruimos Q
Q= np.dot(np.dot(V,A),Vinv)
print(Q)

[[ 3.  0.]
 [ 0. -5.]]


**Ejercicio de práctica** Considere la siguiente matriz:
\begin{align}
 \begin{pmatrix}
 7 & -2 & 4 \\
 -2 & 3 & 6 \\
 4 & 6 & 7 \\
\end{pmatrix}
 \end{align}

 Hallar los valores y vectores propios de esa matriz, y verifique que se puede reconstruir a partir de sus valores y vectores propios.



In [9]:
# Definición de la matriz
M = np.array([[7,-2,4],[-2,3,6],[4,6,7]])

# Autovalores y autovectores
a, V =np.linalg.eig(M)

# Matriz inversa
Vinv = np.linalg.inv(V)

# Reconstrucción de la matriz
A = np.diag(a)
Q = np.dot(np.dot(V,A),Vinv)
Q

array([[ 7., -2.,  4.],
       [-2.,  3.,  6.],
       [ 4.,  6.,  7.]])

**Ejercicio de práctica** Una matriz $Q$ de tamaño $2\times 2$ es simétrica con valores propios $8$ y $3$.  Los vectores propios son

Matriz V:

\begin{align}
 v_1=\begin{pmatrix}
 2/\sqrt{5} \\
 -1/\sqrt{5} \\
\end{pmatrix}
 \end{align}
y
 \begin{align}
 v_2=\begin{pmatrix}
  1/\sqrt{5}\\
  2/\sqrt{5}\\
\end{pmatrix}
 \end{align}.

 Usando esta información, reconstruya la matriz $Q$.



In [16]:
# Matriz de valores propips
A = np.diag([8,3])
V = np.array([[2/np.sqrt(5), -1/np.sqrt(5)], [1/np.sqrt(5), 2/np.sqrt(5)]]).T
Vinv = np.linalg.inv(V)

# Reconstrucción de la martiz
Q = np.dot(np.dot(V,A),Vinv)

# Verificación de lo obtenido
a_rec, v_rec = np.linalg.eig(Q)

print('autovalores')
print(a_rec)
print('autovectores')
print(v_rec)
print('Matriz reconstruida')
Q

autovalores
[8. 3.]
autovectores
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]
Matriz reconstruida


array([[ 7., -2.],
       [-2.,  4.]])